import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Camera, MapPin, Send } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useNavigate } from "react-router-dom";

const Report = () => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [selectedImages, setSelectedImages] = useState<File[]>([]);
  const [formData, setFormData] = useState({
    category: "",
    title: "",
    description: "", 
    location: "",
    latitude: null as number | null,
    longitude: null as number | null
  });
  const { toast } = useToast();
  const { user } = useAuth();
  const navigate = useNavigate();

  const issueTypes = [
    { value: "pothole", label: "Pothole", color: "destructive" },
    { value: "streetlight", label: "Street Light", color: "secondary" },
    { value: "water", label: "Water Leakage", color: "civic" },
    { value: "garbage", label: "Garbage Collection", color: "outline" },
    { value: "drainage", label: "Drainage Issue", color: "destructive" },
    { value: "traffic", label: "Traffic Signal", color: "secondary" },
    { value: "park", label: "Park Maintenance", color: "civic" },
    { value: "other", label: "Other", color: "outline" }
  ];

  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files || []);
    setSelectedImages(prev => [...prev, ...files].slice(0, 5)); // Max 5 images
  };

  const removeImage = (index: number) => {
    setSelectedImages(prev => prev.filter((_, i) => i !== index));
  };

  const getCurrentLocation = () => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          setFormData(prev => ({
            ...prev,
            latitude: position.coords.latitude,
            longitude: position.coords.longitude
          }));
          toast({
            title: "Location detected",
            description: `Lat: ${position.coords.latitude.toFixed(4)}, Lng: ${position.coords.longitude.toFixed(4)}`,
          });
        },
        (error) => {
          toast({
            title: "Location error",
            description: "Unable to get your location. Please enter manually.",
            variant: "destructive",
          });
        }
      );
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!user) {
      toast({
        title: "Please sign in",
        description: "You need to be signed in to report issues.",
        variant: "destructive",
      });
      navigate("/auth");
      return;
    }

    if (!formData.category || !formData.title || !formData.description || !formData.location) {
      toast({
        title: "Missing information",
        description: "Please fill in all required fields.",
        variant: "destructive",
      });
      return;
    }

    setIsSubmitting(true);

    try {
      const { data, error } = await supabase
        .from('civic_reports')
        .insert([{
          user_id: user.id,
          category: formData.category as "pothole" | "streetlight" | "water" | "garbage" | "drainage" | "traffic" | "park" | "other",
          title: formData.title,
          description: formData.description,
          location_text: formData.location,
          latitude: formData.latitude,
          longitude: formData.longitude,
          report_number: '' // Will be auto-generated by trigger
        }])
        .select()
        .single();

      if (error) throw error;
      if (error) throw error;

      toast({
        title: "Issue reported successfully!",
        description: `Your report has been submitted with ID: ${data.report_number}. You can track it in the Track Issues section.`,
      });

      // Reset form
      setFormData({
        category: "",
        title: "",
        description: "",
        location: "",
        latitude: null,
        longitude: null
      });
      setSelectedImages([]);
      
      // Navigate to track page
      setTimeout(() => {
        navigate("/track");
      }, 2000);

    } catch (error: any) {
      console.error('Error submitting report:', error);
      toast({
        title: "Error submitting report",
        description: error.message || "Something went wrong. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-background py-8">
      <div className="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-8 text-center">
          <h1 className="text-3xl font-bold text-foreground mb-4">
            Report Civic Issue
          </h1>
          <p className="text-muted-foreground">
            Help improve your community by reporting civic issues. Your report will be sent to the relevant department.
          </p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Send className="h-5 w-5 text-civic-saffron" />
              Issue Details
            </CardTitle>
            <CardDescription>
              Provide as much detail as possible to help us address the issue quickly.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-6">
              {/* Issue Type */}
              <div>
                <Label htmlFor="issueType">Issue Category *</Label>
                <Select required value={formData.category} onValueChange={(value) => setFormData(prev => ({ ...prev, category: value }))}>
                  <SelectTrigger className="mt-2">
                    <SelectValue placeholder="Select issue type" />
                  </SelectTrigger>
                  <SelectContent>
                    {issueTypes.map((type) => (
                      <SelectItem key={type.value} value={type.value}>
                        <div className="flex items-center gap-2">
                          <Badge variant={type.color as any} className="text-xs">
                            {type.label}
                          </Badge>
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Title */}
              <div>
                <Label htmlFor="title">Issue Title *</Label>
                <Input 
                  id="title"
                  placeholder="Brief description of the issue"
                  required
                  className="mt-2"
                  value={formData.title}
                  onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
                />
              </div>

              {/* Description */}
              <div>
                <Label htmlFor="description">Detailed Description *</Label>
                <Textarea 
                  id="description"
                  placeholder="Provide detailed information about the issue, including when you noticed it and any safety concerns."
                  required
                  className="mt-2 min-h-[100px]"
                  value={formData.description}
                  onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
                />
              </div>

              {/* Location */}
              <div>
                <Label htmlFor="location">Location *</Label>
                <div className="flex gap-2 mt-2">
                  <Input 
                    id="location"
                    placeholder="Enter location or landmark"
                    required
                    className="flex-1"
                    value={formData.location}
                    onChange={(e) => setFormData(prev => ({ ...prev, location: e.target.value }))}
                  />
                  <Button 
                    type="button" 
                    variant="outline" 
                    size="icon"
                    onClick={getCurrentLocation}
                  >
                    <MapPin className="h-4 w-4" />
                  </Button>
                </div>
                <p className="text-xs text-muted-foreground mt-1">
                  Click the location icon to auto-detect your current location
                  {formData.latitude && formData.longitude && (
                    <span className="text-civic-green ml-2">✓ GPS location captured</span>
                  )}
                </p>
              </div>

              {/* Photo Upload */}
              <div>
                <Label>Photos (Optional)</Label>
                <div className="mt-2">
                  <input
                    type="file"
                    accept="image/*"
                    multiple
                    onChange={handleImageUpload}
                    className="hidden"
                    id="image-upload"
                  />
                  <Label 
                    htmlFor="image-upload"
                    className="flex items-center justify-center gap-2 border-2 border-dashed border-muted-foreground/25 rounded-lg p-6 cursor-pointer hover:border-civic-saffron transition-colors"
                  >
                    <Camera className="h-5 w-5 text-muted-foreground" />
                    <span className="text-sm text-muted-foreground">
                      Click to upload photos (Max 5)
                    </span>
                  </Label>
                </div>

                {/* Image Preview */}
                {selectedImages.length > 0 && (
                  <div className="mt-4 grid grid-cols-3 gap-2">
                    {selectedImages.map((image, index) => (
                      <div key={index} className="relative">
                        <img
                          src={URL.createObjectURL(image)}
                          alt={`Preview ${index + 1}`}
                          className="w-full h-20 object-cover rounded-lg"
                        />
                        <button
                          type="button"
                          onClick={() => removeImage(index)}
                          className="absolute -top-1 -right-1 bg-destructive text-white rounded-full w-5 h-5 flex items-center justify-center text-xs"
                        >
                          ×
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Contact Information */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="name">Your Name</Label>
                  <Input 
                    id="name"
                    placeholder="Enter your name"
                    className="mt-2"
                  />
                </div>
                <div>
                  <Label htmlFor="phone">Phone Number</Label>
                  <Input 
                    id="phone"
                    type="tel"
                    placeholder="Enter phone number"
                    className="mt-2"
                  />
                </div>
              </div>

              {/* Submit Button */}
              <div className="pt-4">
                <Button 
                  type="submit" 
                  variant="civic" 
                  className="w-full" 
                  disabled={isSubmitting}
                >
                  {isSubmitting ? (
                    <>
                      <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2" />
                      Submitting Report...
                    </>
                  ) : (
                    <>
                      <Send className="mr-2 h-4 w-4" />
                      Submit Issue Report
                    </>
                  )}
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>

        {/* Information Card */}
        <Card className="mt-6">
          <CardContent className="pt-6">
            <div className="text-center">
              <h3 className="font-medium text-foreground mb-2">What happens next?</h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm text-muted-foreground">
                <div>
                  <div className="font-medium text-civic-saffron">1. Confirmation</div>
                  <p>You'll receive a reference number</p>
                </div>
                <div>
                  <div className="font-medium text-civic-navy">2. Review</div>
                  <p>Department will assess the issue</p>
                </div>
                <div>
                  <div className="font-medium text-civic-green">3. Resolution</div>
                  <p>Action taken and status updated</p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default Report;